/* RELATORIO GERAL DE TODOS OS CLIENTES COM INFORMAÇÕES PERTINENTES */

SOLUÇÃO DA QUESTÃO:

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
       T.TIPO, T.NUMERO
FROM CLIENTE C
LEFT JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY IDCLIENTE;

/* RELATORIO DE HOMENS */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='M';


/* SELECIONAR AS INFORMAÇÕES DOS CLIENTES QUE POSSUEM ID DE: 11, 12 17, 18*/

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.IDCLIENTE = 11 OR C.IDCLIENTE = 13 OR C.IDCLIENTE = 17 OR C.IDCLIENTE = 18;

/* IDENTANDO MELHOR O WHERE ACIMA*/ 

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.IDCLIENTE IN (11,12,17,18);

/* TRAZER TODAS O RELATORIO DE MULHERES */


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='F';

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM CLIENTE GROUP BY SEXO;

/* QUANTIDADE DE MULHERES */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM CLIENTE WHERE SEXO='F' GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E 
NAO TENHAM CELULAR */

SELECT C.IDCLIENTE, C.EMAIL FROM CLIENTE C
LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.CIDADE = 'RIO DE JANEIRO' AND BAIRRO ='CENTRO' AND T.NUMERO IS NULL;

