/* RELATORIO GERAL DE TODOS OS CLIENTES */

SOLUÇÃO DA QUESTÃO:

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE;

