/* RELATORIO GERAL DE TODOS OS CLIENTES COM INFORMAÇÕES PERTINENTES */

SOLUÇÃO DA QUESTÃO:

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
       T.TIPO, T.NUMERO
FROM CLIENTE C
LEFT JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY IDCLIENTE;

/* RELATORIO DE HOMENS */

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='M';


/* SELECIONAR AS INFORMAÇÕES DOS CLIENTES QUE POSSUEM ID DE: 11, 12 17, 18*/

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.IDCLIENTE = 11 OR C.IDCLIENTE = 13 OR C.IDCLIENTE = 17 OR C.IDCLIENTE = 18;

/* IDENTANDO MELHOR O WHERE ACIMA*/ 

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.IDCLIENTE IN (11,12,17,18);

/* TRAZER TODAS O RELATORIO DE MULHERES */


SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.NUMERO, T.TIPO
FROM CLIENTE C LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE  T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='F';

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM CLIENTE GROUP BY SEXO;

/* QUANTIDADE DE MULHERES */

SELECT SEXO, COUNT(*) AS QUANTIDADE FROM CLIENTE WHERE SEXO='F' GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E 
NAO TENHAM CELULAR */

SELECT C.IDCLIENTE, C.EMAIL, T.TIPO FROM CLIENTE C
LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.CIDADE = 'RIO DE JANEIRO' AND BAIRRO ='CENTRO' AND T.TIPO != 'CEL';

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO, T.TIPO, E.ESTADO FROM CLIENTE C
LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE T.TIPO ='CEL'  AND E.ESTADO = 'RJ';

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */


SELECT C.NOME, C.EMAIL, T.NUMERO, T.TIPO, E.CIDADE FROM CLIENTE C
LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO ='F'  AND E.ESTADO = 'SP';

/* nome, email, numero, estado */

SELECT C.NOME, C.EMAIL, T.NUMERO, E.ESTADO FROM CLIENTE C
LEFT JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
LEFT JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE;
'



